
development:
  adapter: postgresql
  encoding: unicode
  database: example_development
  pool: 5
  username: example
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: example_development
  pool: 5
  username: example
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: example_development
  pool: 5
  username: example
  password:
